# Generated by Django 4.0.1 on 2022-03-02 17:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('email', models.EmailField(blank=True, max_length=200, null=True)),
                ('user_name', models.CharField(max_length=200)),
                ('short_intro', models.CharField(blank=True, max_length=200, null=True)),
                ('Bio', models.TextField(blank=True, null=True)),
                ('auth_image', models.ImageField(blank=True, null=True, upload_to='static/blogging/authors')),
                ('instagram', models.CharField(max_length=200)),
                ('linkedin', models.CharField(max_length=200)),
                ('snap_chat', models.CharField(max_length=200, null=True)),
                ('github', models.CharField(max_length=200)),
                ('sign_up', models.DateTimeField(auto_now_add=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['sign_up'],
            },
        ),
    ]
